# Generated by Django 2.0.7 on 2020-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20200517_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Detail Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(blank=True, max_length=200, verbose_name='Preview Text'),
        ),
    ]
