# Generated by Django 2.0.7 on 2020-05-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20200517_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_text',
        ),
    ]
