# Generated by Django 2.0.7 on 2020-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20200517_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
