# Generated by Django 2.0.7 on 2020-05-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
