# Generated by Django 2.0.7 on 2020-05-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
