# Generated by Django 2.0.7 on 2020-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denim', '0002_auto_20200512_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='denimmen',
            name='slug',
            field=models.SlugField(default=1),
        ),
        migrations.AddField(
            model_name='denimwomen',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
