# Generated by Django 2.0.7 on 2020-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='category',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
