# Generated by Django 2.0.7 on 2020-05-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brands_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='category',
            new_name='categoryname',
        ),
    ]
