# Generated by Django 2.0.7 on 2020-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brands_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='link',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
