# Generated by Django 2.0.7 on 2020-05-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20200510_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('price', models.IntegerField(blank=True)),
                ('categoryname', models.CharField(max_length=120)),
                ('link', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
