# Generated by Django 2.0.7 on 2020-05-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brands_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands_detail',
            new_name='Levis_brand_detail',
        ),
    ]
