# Generated by Django 2.0.7 on 2020-05-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20200511_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levis_brand_detail',
            new_name='Brands_detail',
        ),
    ]
