# Generated by Django 2.0.7 on 2020-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_auto_20200511_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands_detail',
            name='brand_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
