# Generated by Django 2.0.7 on 2020-05-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formal', '0002_auto_20200507_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalmen',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='formalwomen',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
