# Generated by Django 2.0.7 on 2020-05-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualmenpant',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='casualment',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='casualwomenpant',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='casualwoment',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
