# Generated by Django 2.0.7 on 2020-05-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='url',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
